# Generated by Django 5.2.4 on 2025-07-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegevisit',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
