# Generated by Django 5.2.4 on 2025-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientvisit',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='clientvisit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
    ]
