# Generated by Django 5.2.4 on 2025-08-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_clientvisit_created_at_collegevisit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvisit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collegevisit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='officevisit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='onlineclassinquiry',
            name='created_at',
        ),
    ]
